language: java

os:
  - linux
  - osx

before_script: scripts/travis-setup.sh

script: ~/bin/sbt -Dorg.slf4j.simpleLogger.defaultLogLevel=debug +test

cache:
  - directories:
    - $HOME/install
    - $HOME/.isabelle
